CREATE Table users (
  user_id integer AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  email varchar(100) NOT NULL,
  password varchar(100) NOT NULL,
  created_at timestamp,
  PRIMARY KEY (user_id)
);

CREATE Table tokens (
  id_token int AUTO_INCREMENT NOT NULL,
  user_id int(11) NOT NULL,
  token text NOT NULL,
  expires_at timestamp NOT NULL,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (id_token),
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE symptoms (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symptom VARCHAR(255) NOT NULL
);

INSERT INTO symptoms (symptom) VALUES
('Itching'),
('Skin rash'),
('Continuous sneezing'),
('Shivering'),
('Stomach pain'),
('Acidity'),
('Vomiting'),
('Indigestion'),
('Muscle wasting'),
('Patches in throat'),
('Fatigue'),
('Weight loss'),
('Sunken eyes'),
('Cough'),
('Headache'),
('Chest pain'),
('Back pain'),
('Weakness in limbs'),
('Chills'),
('Joint pain'),
('Yellowish skin'),
('Constipation'),
('Pain during bowel movements'),
('Breathlessness'),
('Cramps'),
('Weight gain'),
('Mood swings'),
('Neck pain'),
('Muscle weakness'),
('Stiff neck'),
('Pus filled pimples'),
('Burning micturition'),
('Bladder discomfort'),
('High fever'),
('Nodal skin eruptions'),
('Ulcers on tongue'),
('Loss of appetite'),
('Restlessness'),
('Dehydration'),
('Dizziness'),
('Weakness of one body side'),
('Lethargy'),
('Nausea'),
('Abdominal pain'),
('Pain in anal region'),
('Sweating'),
('Bruising'),
('Cold hands and feet'),
('Anxiety'),
('Knee pain'),
('Swelling joints'),
('Blackheads'),
('Foul smell of urine'),
('Skin peeling'),
('Blister'),
('Dischromic patches'),
('Watering from eyes'),
('Extra marital contacts'),
('Diarrhoea'),
('Loss of balance'),
('Blurred and distorted vision'),
('Altered sensorium'),
('Dark urine'),
('Swelling of stomach'),
('Bloody stool'),
('Obesity'),
('Hip joint pain'),
('Movement stiffness'),
('Spinning movements'),
('Scurring'),
('Continuous feel of urine'),
('Silver-like dusting'),
('Red sore around nose'),
('Fever'),
('Spotting urination'),
('Passage of gases'),
('Irregular sugar level'),
('Family history'),
('Lack of concentration'),
('Excessive hunger'),
('Yellowing of eyes'),
('Distention of abdomen'),
('Irritation in anus'),
('Swollen legs'),
('Painful walking'),
('Small dents in nails'),
('Yellow crust ooze'),
('Internal itching'),
('Mucoid sputum'),
('History of alcohol consumption'),
('Swollen blood vessels'),
('Unsteadiness'),
('Inflammatory nails'),
('Depression'),
('Fluid overload'),
('Swollen lymph nodes'),
('Malaise'),
('Prominent veins on calf'),
('Puffy face and eyes'),
('Fast heart rate'),
('Irritability'),
('Muscle pain'),
('Mild fever'),
('Yellow urine'),
('Phlegm'),
('Enlarged thyroid'),
('Increased appetite'),
('Visual disturbances'),
('Brittle nails'),
('Drying and tingling lips'),
('Polyuria'),
('Pain behind the eyes'),
('Toxic look (typhos)'),
('Throat irritation'),
('Swollen extremities'),
('Slurred speech'),
('Red spots over body'),
('Belly pain'),
('Receiving blood transfusion'),
('Acute liver failure'),
('Redness of eyes'),
('Rusty sputum'),
('Abnormal menstruation'),
('Receiving unsterile injections'),
('Coma'),
('Sinus pressure'),
('Palpitations'),
('Stomach bleeding'),
('Runny nose'),
('Congestion'),
('Blood in sputum'),
('Loss of smell');

